<?= $this->extend('layouts/auth') ?>
<?= $this->section('content') ?>
<div class="auth-intro"><h1>Buat akun baru</h1><p>Daftarkan akun pengelola untuk mulai menambahkan jurnal dan melakukan evaluasi.</p></div>
<?php if (session('errors')): ?><div class="auth-alert error" role="alert"><?= esc(implode(' ', session('errors'))) ?></div><?php endif ?>
<?php if (session('error')): ?><div class="auth-alert error" role="alert"><?= esc(session('error')) ?></div><?php endif ?>
<form class="auth-form" method="post" action="<?= site_url('register') ?>">
    <?= csrf_field() ?>
    <label class="form-field"><span class="field-label">Username <span class="required">*</span></span><span class="input-wrap"><svg class="input-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="8" r="3.5"/><path d="M5 20a7 7 0 0 1 14 0"/></svg><input type="text" name="username" value="<?= esc(old('username')) ?>" placeholder="Nama pengguna" autocomplete="username" minlength="3" maxlength="80" required autofocus></span></label>
    <label class="form-field"><span class="field-label">Email <span class="required">*</span></span><span class="input-wrap"><svg class="input-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/></svg><input type="email" name="email" value="<?= esc(old('email')) ?>" placeholder="nama@email.com" autocomplete="email" required></span></label>
    <label class="form-field"><span class="field-label">Kata sandi <span class="required">*</span></span><span class="input-wrap"><svg class="input-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg><input id="register-password" type="password" name="password" placeholder="Minimal 8 karakter" autocomplete="new-password" minlength="8" required><button class="password-toggle" type="button" data-password-toggle="register-password" aria-label="Tampilkan kata sandi" aria-pressed="false"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.5"/></svg></button></span></label>
    <label class="form-field"><span class="field-label">Konfirmasi kata sandi <span class="required">*</span></span><span class="input-wrap"><svg class="input-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg><input id="register-password-confirm" type="password" name="password_confirm" placeholder="Ulangi kata sandi" autocomplete="new-password" minlength="8" required><button class="password-toggle" type="button" data-password-toggle="register-password-confirm" aria-label="Tampilkan kata sandi" aria-pressed="false"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.5"/></svg></button></span></label>
    <button class="submit-button" type="submit">Daftar</button>
</form>
<div class="auth-divider">sudah memiliki akun?</div>
<a class="secondary-link" href="<?= site_url('login') ?>">Kembali ke halaman masuk</a>
<?= $this->endSection() ?>
