<?= $this->extend('layouts/admin') ?>
<?= $this->section('content') ?>
<style>
.account-page{max-width:920px;margin:0 auto}.account-hero{position:relative;overflow:hidden;display:flex;align-items:center;gap:16px;padding:23px 25px;border-radius:16px;background:linear-gradient(125deg,#173f75,#2b68a9);color:#fff;box-shadow:0 12px 28px rgba(23,63,117,.14)}.account-avatar{width:54px;height:54px;flex:none;display:grid;place-items:center;border-radius:15px;background:#fff;color:#17477d;font-size:1.1rem;font-weight:800}.account-hero h1{margin:0;font-size:1.45rem}.account-hero p{margin:6px 0 0;color:#d9e9fa;font-size:.74rem}.account-card{margin-top:17px;padding:24px;border:1px solid #dfe7ef;border-radius:15px;background:#fff;box-shadow:0 7px 22px rgba(25,48,76,.055)}.account-section+.account-section{margin-top:23px;padding-top:21px;border-top:1px solid #e7edf3}.account-section h2{margin:0;font-size:1rem}.account-section>p{margin:5px 0 15px;color:#718397;font-size:.7rem}.account-grid{display:grid;grid-template-columns:1fr 1fr;gap:15px}.account-card label{margin:0;color:#2d455c;font-size:.72rem;font-weight:600}.account-card input{height:44px;margin-top:7px;padding:0 13px;border-color:#ccd9e6;border-radius:9px;background:#fbfcfe}.password-control{position:relative}.password-control input{padding-right:44px}.password-toggle{position:absolute;right:7px;bottom:5px;width:34px;height:34px;padding:0;display:grid;place-items:center;border-radius:8px;background:transparent;color:#617991}.password-toggle:hover{background:#eaf2fb;color:#17477d}.password-toggle svg{width:17px;height:17px}.current-password{max-width:calc(50% - 7px);margin-top:15px!important}.account-note{margin-top:15px;padding:12px 14px;border-left:4px solid #2f78b9;border-radius:8px;background:#eff7ff;color:#416584;font-size:.7rem;line-height:1.55}.account-actions{display:flex;justify-content:flex-end;margin-top:20px}.save-account{min-height:42px;padding:0 16px;border-radius:9px}.flash,.account-error{margin:15px 0 0}.account-error{padding:12px 14px;border-radius:9px;background:#fff0ef;color:#a72d25;font-size:.72rem}@media(max-width:650px){.account-grid{grid-template-columns:1fr}.current-password{max-width:none}.account-card{padding:19px}.save-account{width:100%}}
</style>
<?php
$name = (string) old('name', $user['name']);
$parts = preg_split('/\s+/', trim($name)) ?: ['A'];
$initials = implode('', array_map(static fn (string $part): string => strtoupper(substr($part, 0, 1)), array_slice($parts, 0, 2)));
?>
<div class="account-page">
    <header class="account-hero"><span class="account-avatar"><?= esc($initials ?: 'A') ?></span><div><h1>Pengaturan Akun</h1><p><?= esc(str_replace('_', ' ', (string) $user['role'])) ?> · Kelola identitas dan keamanan akun Anda.</p></div></header>
    <?php if (session('success')): ?><p class="flash"><?= esc(session('success')) ?></p><?php endif ?>
    <?php if (session('errors')): ?><div class="account-error"><?= esc(implode(' ', session('errors'))) ?></div><?php endif ?>
    <?php if (session('error')): ?><div class="account-error"><?= esc(session('error')) ?></div><?php endif ?>
    <form class="account-card" method="post" action="<?= site_url('akun') ?>"><?= csrf_field() ?>
        <section class="account-section"><h2>Informasi profil</h2><p>Nama ini ditampilkan pada dashboard dan sidebar aplikasi.</p><div class="account-grid"><label>Nama lengkap<input name="name" required minlength="3" maxlength="120" value="<?= esc(old('name', $user['name'])) ?>" autocomplete="name"></label><label>Email<input name="email" type="email" required maxlength="191" value="<?= esc(old('email', $user['email'])) ?>" autocomplete="email"></label></div></section>
        <section class="account-section"><h2>Ganti kata sandi</h2><p>Kosongkan kedua kolom berikut apabila tidak ingin mengganti kata sandi.</p><div class="account-grid"><label>Kata sandi baru<div class="password-control"><input id="new-password" name="new_password" type="password" minlength="8" maxlength="72" autocomplete="new-password"><button class="password-toggle" type="button" data-password-target="new-password" aria-label="Tampilkan kata sandi"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.5"/></svg></button></div></label><label>Konfirmasi kata sandi baru<div class="password-control"><input id="new-password-confirm" name="new_password_confirm" type="password" minlength="8" maxlength="72" autocomplete="new-password"><button class="password-toggle" type="button" data-password-target="new-password-confirm" aria-label="Tampilkan konfirmasi kata sandi"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.5"/></svg></button></div></label></div></section>
        <label class="current-password">Kata sandi saat ini<div class="password-control"><input id="current-password" name="current_password" type="password" required maxlength="72" autocomplete="current-password"><button class="password-toggle" type="button" data-password-target="current-password" aria-label="Tampilkan kata sandi saat ini"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.5"/></svg></button></div></label>
        <div class="account-note"><strong>Konfirmasi keamanan.</strong> Kata sandi saat ini wajib diisi untuk menyimpan perubahan nama, email, maupun kata sandi.</div>
        <div class="account-actions"><button class="save-account" type="submit">Simpan Pengaturan</button></div>
    </form>
</div>
<script>
document.querySelectorAll('[data-password-target]').forEach(button=>button.addEventListener('click',()=>{const input=document.getElementById(button.dataset.passwordTarget);const showing=input.type==='text';input.type=showing?'password':'text';button.setAttribute('aria-label',showing?'Tampilkan kata sandi':'Sembunyikan kata sandi');}));
</script>
<?= $this->endSection() ?>
