<?= $this->extend('layouts/admin') ?>
<?= $this->section('content') ?>
<style>
.users-page{max-width:1180px;margin:0 auto}.users-head{margin-bottom:1.5rem}.users-head h1{margin:.2rem 0 0;font-size:2rem;line-height:1.2}.users-head p{margin:0;color:#64748b}.users-note{margin-bottom:1rem;padding:.9rem 1rem;border:1px solid #cfe0f1;border-radius:10px;background:#f3f8fe;color:#426584;font-size:.78rem;line-height:1.55}.list-card{overflow:hidden;border:1px solid #e2e8f0;border-radius:12px;background:#fff;box-shadow:0 4px 18px rgba(25,48,76,.055)}.users-table-wrap{overflow-x:auto}.users-table{min-width:760px;margin:0}.users-table th{padding:.85rem 1rem;background:#f8fafc;color:#475569;font-size:.76rem;letter-spacing:.04em;text-transform:uppercase}.users-table td{padding:1rem;border-bottom:1px solid #e2e8f0;font-size:.86rem;vertical-align:middle}.users-table tbody tr:hover{background:#f8fbff}.user-name{display:block;font-size:.92rem;font-weight:700}.user-email{display:block;margin-top:.25rem;color:#64748b;font-size:.78rem}.account-state{display:inline-flex;padding:.3rem .65rem;border-radius:999px;background:#ecfdf3;color:#067647;font-size:.76rem;font-weight:700}.account-state.off{background:#f1f5f9;color:#64748b}.status-form{margin:0;text-align:right}.status-button{width:132px;height:38px;min-height:38px;margin:0;padding:0;border:1px solid #cbd5e1;border-radius:7px;background:#fff;color:#425b73;font-size:.78rem}.status-button:hover{background:#f1f5f9}.flash{margin:0 0 1rem}.empty{padding:2.5rem;text-align:center;color:#64748b}
@media(max-width:620px){.users-table-wrap{overflow:visible}.users-table{min-width:0}.users-table thead{display:none}.users-table,.users-table tbody,.users-table tr,.users-table td{display:block;width:100%}.users-table tr{margin-bottom:1rem;padding:1rem;border:1px solid #e2e8f0;border-radius:10px}.users-table td{display:grid;grid-template-columns:105px 1fr;gap:.75rem;padding:.6rem 0;border:0}.users-table td::before{content:attr(data-label);color:#64748b;font-size:.75rem;font-weight:700;text-transform:uppercase}.users-table td:last-child{display:block;padding-top:.9rem}.users-table td:last-child::before{display:none}.status-form{text-align:left}}
</style>
<div class="users-page">
    <header class="users-head"><p>Pengelolaan akses teknis</p><h1>Pengguna</h1></header>
    <div class="users-note">Akun dibuat melalui halaman registrasi. Operator hanya dapat mengaktifkan atau menonaktifkan akses dan tidak dapat membuka data jurnal maupun hasil evaluasi pengguna.</div>
    <?php if (session('success')): ?><p class="flash"><?= esc(session('success')) ?></p><?php endif ?>
    <section class="list-card"><?php if ($users === []): ?><div class="empty">Belum ada pengguna yang terdaftar.</div><?php else: ?><div class="users-table-wrap"><table class="users-table"><thead><tr><th>Pengguna</th><th>Jurnal mandiri</th><th>Status akun</th><th style="text-align:right">Aksi</th></tr></thead><tbody><?php foreach ($users as $user): ?><tr><td data-label="Pengguna"><span class="user-name"><?= esc($user['name']) ?></span><span class="user-email"><?= esc($user['email']) ?></span></td><td data-label="Jurnal"><strong><?= (int) $user['journal_count'] ?></strong> jurnal</td><td data-label="Status"><span class="account-state <?= $user['is_active'] ? '' : 'off' ?>"><?= $user['is_active'] ? 'Aktif' : 'Nonaktif' ?></span></td><td data-label="Aksi"><form class="status-form" method="post" action="<?= site_url('admin/admin-jurnal/' . $user['id'] . '/status') ?>" onsubmit="return confirm('Ubah status akses pengguna ini?')"><?= csrf_field() ?><button class="status-button" type="submit"><?= $user['is_active'] ? 'Nonaktifkan' : 'Aktifkan' ?></button></form></td></tr><?php endforeach ?></tbody></table></div><?php endif ?></section>
</div>
<?= $this->endSection() ?>
