<?= $this->extend('layouts/admin') ?>
<?= $this->section('content') ?>
<style>
.operator-page{max-width:1280px;margin:0 auto}.operator-hero{position:relative;overflow:hidden;padding:30px 34px;border-radius:18px;background:linear-gradient(125deg,#173f75,#2b69aa);color:#fff;box-shadow:0 14px 34px rgba(23,63,117,.16)}.operator-hero:after{content:"";position:absolute;right:-70px;top:-145px;width:320px;height:320px;border:1px solid rgba(255,255,255,.14);border-radius:50%;box-shadow:0 0 0 44px rgba(255,255,255,.04),0 0 0 88px rgba(255,255,255,.025)}.operator-kicker{position:relative;z-index:1;margin:0 0 8px;color:#cce2fa;font-size:.75rem;font-weight:700;letter-spacing:.1em;text-transform:uppercase}.operator-hero h1{position:relative;z-index:1;margin:0;font-size:2.15rem}.operator-hero p:last-child{position:relative;z-index:1;max-width:720px;margin:9px 0 0;color:#dceafa;font-size:.86rem;line-height:1.55}.stat-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:1rem;margin:1.25rem 0}.stat-card{padding:1.2rem;border:1px solid #e2e8f0;border-radius:12px;background:#fff;box-shadow:0 5px 18px rgba(25,48,76,.05)}.stat-card span{display:block;color:#64748b;font-size:.78rem}.stat-card strong{display:block;margin-top:.4rem;color:#173f75;font-size:1.7rem}.operator-card{overflow:hidden;border:1px solid #e2e8f0;border-radius:14px;background:#fff;box-shadow:0 5px 20px rgba(25,48,76,.055)}.operator-card-head{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:1.4rem 1.5rem;border-bottom:1px solid #e2e8f0}.operator-card-head h2{margin:0;font-size:1.15rem}.operator-card-head p{margin:.35rem 0 0;color:#64748b;font-size:.78rem}.manage-button{width:132px;height:42px;min-height:42px;padding:0;border-radius:8px;font-size:.8rem}.user-table{margin:0}.user-table th{padding:.85rem 1rem;background:#f8fafc;color:#475569;font-size:.75rem;letter-spacing:.04em;text-transform:uppercase}.user-table td{padding:1rem;border-bottom:1px solid #e2e8f0;font-size:.84rem;vertical-align:middle}.user-name{display:block;font-weight:700}.user-email{display:block;margin-top:.2rem;color:#64748b;font-size:.76rem}.state{display:inline-flex;padding:.3rem .65rem;border-radius:999px;background:#ecfdf3;color:#067647;font-size:.73rem;font-weight:700}.state.off{background:#f1f5f9;color:#64748b}.empty{padding:2.5rem;text-align:center;color:#64748b}.operator-note{margin-top:1.25rem;padding:1rem 1.1rem;border:1px solid #cfe0f1;border-radius:10px;background:#f3f8fe;color:#426584;font-size:.78rem;line-height:1.55}
@media(max-width:900px){.stat-grid{grid-template-columns:1fr 1fr}}@media(max-width:620px){.operator-hero{padding:24px}.operator-hero h1{font-size:1.7rem}.stat-grid{grid-template-columns:1fr}.operator-card-head{align-items:flex-start;flex-direction:column}.manage-button{width:100%}.user-table th:nth-child(2),.user-table td:nth-child(2){display:none}}
</style>
<div class="operator-page">
    <header class="operator-hero"><p class="operator-kicker">Operator teknis</p><h1>Pengelolaan akun pengguna</h1><p>Area ini hanya digunakan untuk menjaga akses akun. Operator tidak dapat melihat atau mengubah jurnal, checklist, bukti, maupun nilai simulasi pengguna.</p></header>

    <section class="stat-grid" aria-label="Ringkasan pengguna">
        <article class="stat-card"><span>Total pengguna</span><strong><?= $stats['users'] ?></strong></article>
        <article class="stat-card"><span>Akun aktif</span><strong><?= $stats['active'] ?></strong></article>
        <article class="stat-card"><span>Akun nonaktif</span><strong><?= $stats['inactive'] ?></strong></article>
        <article class="stat-card"><span>Pengguna baru bulan ini</span><strong><?= $stats['new_this_month'] ?></strong></article>
    </section>

    <section class="operator-card">
        <div class="operator-card-head"><div><h2>Pengguna terbaru</h2><p>Daftar ringkas akun yang baru melakukan registrasi.</p></div><a class="button manage-button" href="<?= site_url('admin/admin-jurnal') ?>">Kelola Pengguna</a></div>
        <?php if ($recentUsers === []): ?><div class="empty">Belum ada pengguna yang terdaftar.</div><?php else: ?><table class="user-table"><thead><tr><th>Pengguna</th><th>Tanggal registrasi</th><th>Status</th></tr></thead><tbody><?php foreach ($recentUsers as $user): ?><tr><td><span class="user-name"><?= esc($user['name']) ?></span><span class="user-email"><?= esc($user['email']) ?></span></td><td><?= esc($user['created_at'] ? date('d M Y, H:i', strtotime($user['created_at'])) : '-') ?></td><td><span class="state <?= $user['is_active'] ? '' : 'off' ?>"><?= $user['is_active'] ? 'Aktif' : 'Nonaktif' ?></span></td></tr><?php endforeach ?></tbody></table><?php endif ?>
    </section>
    <div class="operator-note"><strong>Batas kewenangan operator:</strong> pengelolaan isi jurnal dan seluruh hasil simulasi tetap dilakukan secara mandiri oleh pemilik akun masing-masing.</div>
</div>
<?= $this->endSection() ?>
